[tool.poetry]
name = "tracking"
version = "0.1.0"
description = ""
authors = ["harrisDLEng <harris@goclever.io>", "Jorge Garcia <jorge@goclever.io>", "Vasco Andrade e Silva <vasco@goclever.io>"]
readme = "README.md"
packages = [
    {include = "tracking/detection_frontend_api", from = "bases" },
    {include = "tracking/tag_detection", from = "bases" },
    {include = "tracking/inc", from = "components" },
    {include = "tracking/log", from = "components" },
    {include = "development" },
    {include = "tracking/yolox_trainer",from = "bases"},
    {include = "tracking/models",from = "components"},
    {include = "tracking/core",from = "components"},
]


[tool.poetry.dependencies]
python = "^3.10"
torch = "^2.0.1"
torchvision = "^0.15.2"
notebook = "^7.0.4"
pandas = "^2.1.2"
flask = "^3.0.0"
gunicorn = "^21.2.0"
seaborn = "^0.13.0"
scipy = "^1.11.3"
pytest-lazy-fixture = "^0.6.3"
flask-lambda-python36 = "^0.1.1"
flask-cors = "^4.0.0"
dacite = "^1.8.1"
roboflow = "^1.1.16"
loguru = "^0.7.2"
tabulate = "^0.9.0"
thop = "^0.1.1.post2209072238"
sagemaker = "^2.210.0"
fastapi = "^0.110.0"
uvicorn = {extras = ["standard"], version = "^0.29.0"}
structlog = "^24.1.0"
mangum = "^0.17.0"
shapely = "^2.0.3"
pydantic-settings = "^2.2.1"
python-multipart = "^0.0.9"
pytest-asyncio = "^0.23.6"
httpx = "^0.27.0"
asyncpg = "^0.29.0"
aiocache = "^0.12.2"
boto3 = "^1.34.110"
opencv-python = "^4.9.0.80"
botocore = "^1.34.110"
scikit-learn = "^1.5.0"
awslambdaric = "^2.0.11"
packaging = "^24.1"
setuptools = "^70.0.0"
pillow = "^10.3.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
awscli = "^1.32.94"
boto3-stubs = {extras = ["kinesis-video-archived-media", "s3", "lambda"], version = "^1.34.110"}
mypy-boto3 = "^1.34.94"
mypy = "^1.10.0"
ruff = "^0.4.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "-vv"

[tool.pyright]
extraPaths = ["bases", "components"]